export const chEnTextHtml = {
  "TC":{
      common : "共",
      ban : "版",
      ban2 : "版",
      currentban : "當前版號：",
      productdescription : "商品描述",
      nointroduction : "暫無介紹",
      noinformation : "暫無更多資訊",
      downloadFile : "下載原始文件副本",
      currentholdings : "當前持有可鑄造版號：",
      notyet : "暫無",
      mint : "鑄造中",
      inpreparation : "(功能準備中)",
      norecord : "暫無藏品記錄",
      more : "加载更多",
      linkwallet : "您需要連接錢包",
      tips1 : "為了接收您的NFT,您需要先連接錢包。",
      tips2 : "如果您不熟悉加密貨幣錢包,請單擊此處。",
      tips3 : '成功出售後，平臺扣除2%手續費，剩余金額將會自動發送至該NFT出售前所在錢包，該NFT將自動發送至買家錢包。',
      tips4 : '填寫出售價格',
      connectnow : "立即連接",
      banhao : "版號",
      jsaddress : "接收地址: ",
      editaddress : "(默認為當前連接的錢包地址，點擊修改)",
      banhao2 : "版號",
      jsaddress2 : "暫無接收地址",
      editaddress2 : "(默認為當前連接的錢包地址，點擊修改)",
      startmint : "開始鑄造",
      dqwmintbanhao : "當前無可鑄造版號",
      tipsjs1:'不可以為空~',
      tipsjs2:'请输入合法地址',
      tipsjs3:'修改成功',
      tipsjs4:'轉移操作已完成~',
      tipsjs5:'您的NFT轉移操作已完成，請到相應錢包內確認噢~',
      currentlyholds:"當前持有",
      blockchain:"區塊鏈：",
      inwallet:"當前所在錢包: ",
      edit:"修改",
      clickedit:"點擊修改地址",
      transfer:"轉移",
      sell:"出售",
      cancel:"取消",
      bootomtips : 'NFT鑄造將在每個工作日中午12點進行，鑄造前一天所銷售的所有NFT。',
      submit : "提交",
      sellnft : "出售NFT",
      empowermodify_words1 : "授權",
      empowermodify_words2 : "首次在Marketplace出售該類型NFT需要授權八爪娛智能合約對您錢包內的NFT進行操作，是否授權？",
      empowermodify_words3 : "Notice:  授權需支付少量GAS費",
      empowermodify_words4 : "否",
      empowermodify_words5 : "是",
      quantity: '數量'
    },
    "EN":{
      quantity: 'quantity',
      bootomtips : 'NFT minting will be done by 11:59 am on every workday for all the NFT sold before this time.',
      common : "Total editions ",
      ban : "",
      ban2 : "Edition",
      productdescription : "Description",
      nointroduction : "No Introduction",
      noinformation : "No more information",
      downloadFile : "Download the original copy",
      currentholdings : "Current mintable editions：",
      notyet : "Null",
      mint : "Minting ",
      inpreparation : "(function coming soon)",
      norecord : "There's nothing here.",
      more : "Load More",
      linkwallet : "Please connect your wallet",
      tips1 : "You need to connect your wallet first in order to receive NFTs",
      tips2 : "",
      tips3 : '成功出售後，平臺扣除2%手續費，剩余金額將會自動發送至該NFT出售前所在錢包，該NFT將自動發送至買家錢包。',
      tips4 : '填寫出售價格',
      connectnow : "Connect now",
      banhao : "Edition",
      jsaddress : "Receiving add: ",
      editaddress : "(Click address to edit if need)",
      banhao2 : "Version Number",
      jsaddress2 : "No receiving address",
      editaddress2 : "(The default is the currently connected wallet address, click to modify)",
      startmint : "Start to mint",
      dqwmintbanhao : "There are no minable editions now :",
      tipsjs1:'Cannot be empty~',
      tipsjs2:'Please enter legal address',
      tipsjs3:'Modified successfully',
      tipsjs4:'Transfer operation completed~',
      tipsjs5:'Modification succeeded. Your NFT transfer operation has been completed. Please confirm in the corresponding wallet~',
      currentlyholds:"Currently holds ",
      blockchain:"Blockchain：",
      inwallet:"In wallet: ",
      edit:"Edit",
      clickedit:"Click to edit",
      transfer:"Transfer",
      sell:"出售",
      cancel:"cancel",
      submit : "提交",
      sellnft : "出售NFT",
      empowermodify_words1 : "授權",
      empowermodify_words2 : "首次在Marketplace出售該類型NFT需要授權八爪娛智能合約對您錢包內的NFT進行操作，是否授權？",
      empowermodify_words3 : "Notice:  授權需支付少量GAS費",
      empowermodify_words4 : "否",
      empowermodify_words5 : "是",
  }
}